### ISSUE TITLE
Unity 2018.2.10f1 64-bit crash on play

### ISSUE THREAD

**Issue by sophiepeithos** [Unity-Technologies/UniteAustinTechnicalPresentation#7]

**Comment by Zifkan** [comment]
Same for me, but 2018.2.9f1 64bit version

**Comment by amechtley** [comment]
Thanks, both, for reporting this! I have actually been investigating this problem and will let you know when we have a fix

**Comment by amechtley** [comment]
Closing since this demo is effectively no longer maintained (in favor of Megacity)
